### PR TITLE
Add more keywords

### LINKED ISSUE #14: Support missing keywords
The following keywords (https://cmake.org/cmake/help/v3.5/command/if.html) are currently not highlighted atm. These are just examples, there might be others missing:
* `MATCHES`
* `STR*`
* `VERSION_*`
* `IN_LIST`

The comment in the code (https://github.com/lucas-clemente/language-cmake/blob/e592aafeb0798a6af24b72bff3d7dc388c86157a/grammars/cmake%20listfile.cson#L59) suggests that the list can be updated somehow automatically. From the text alone I couldn't figure out how this should be done. Is there any more information about that process? Then I would be happy to provide a PR for this.

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #14.

Since the diff is kind of hard to read:

The first commit adds the function `cmake_parse_arguments` and removes the entry `a` (which seems to be wrong, I don't think a function with that name exists?).

The second commit adds the following keywords:

* `EXISTS`
* `IN_LIST`
* `IS_ABSOLUTE`
* `IS_DIRECTORY`
* `IS_NEWER_THAN`
* `IS_SYMLINK`
* `LANGUAGES`
* `MATCHES`
* `NOT`
* `POLICY`
* `STREQUAL`
* `STRGREATER`
* `STRLESS`
* `VERSION_EQUAL`
* `VERSION_GREATER`
* `VERSION_LESS`

### CODE REVIEW

**Comment by lucas-clemente** [comment]
Thanks! 👍

**Comment by dirk-thomas** [comment]
Thank you for the quick merge. Could this maybe be made available in a new patch release?

**Comment by lucas-clemente** [comment]
Will do that tonight.

**Comment by dirk-thomas** [comment]
:+1:

**Comment by lucas-clemente** [comment]
Done

**Comment by dirk-thomas** [comment]
Great, thanks again!

**Pull request merged**
